  Pic/Shape[m
  Register/page[m
  add-doctor/page[m
  add-page[m
  database/data[m
  delete-page[m
* [32mdeploy[m
  deployment[m
  dev[m
  fetch-data[m
  fixing[m
  front/testing[m
  icon[m
  main[m
  menubar[m
  my-appointment/page[m
  nav/bug[m
  navigation[m
  pic-icons/fix[m
  project-setup[m
  reservation[m
  restore/AddDoctor[m
  sidenav[m
  sidnav-border[m
  sign/function[m
  svg/ErrorHandling[m
  svgs[m
  user-api[m
